version: '3.8'
services:
  frontend:
    build: ./Frontend/SmartLibrary
    ports:
      - "3000:80"
    depends_on:
      - springboot

  springboot:
    build: ./Backend/SmartLibrary
    ports:
      - "8080:8080"
    depends_on:
      - flask
  
  flask:
    build: ./Ai/FlaskApp
    ports:
      - "5000:5000"
